### ISSUE TITLE
Deleting cluster is bad news bears

### ISSUE THREAD

**Issue by rgbkrk** [carolynvs/howtowhale#11]
I deleted my howtowhale cluster then tried to visit howtowhale.com again. This resulted in a long wait followed by a 504 Gateway Time-out.

**Comment by rgbkrk** [comment]
As for why I deleted it, I wanted to see the OAuth in action again. Probably good to figure this one out too.

**Comment by carolynvs** [comment]
Thanks for the heads up! _hauls out her sledge hammer and saunters off to fix some bugs_

**Comment by carolynvs** [comment]
If you want to see the oauth dance again, delete the oauth.getcarina.com cookies. Even if you delete your cluster, you won't see the full dance otherwise. Cookies are a delicious, and powerful, treat!

Seriously though, I'm opening up a bug for a better logout. We may want to switch oauth to not use rails cookies for sessions, seems like it's nothing but trouble...

**Comment by rgbkrk** [comment]
:cookie: deleted!

> We may want to switch oauth to not use rails cookies for sessions, seems like it's nothing but trouble...

Yeah...

**Comment by rgbkrk** [comment]
Looking good! I tried out the oauth again for fun was great. I mostly wanted to see if it didn't make me login if I already authenticated with oauth.getcarina.com

**Comment by carolynvs** [comment]
When fixing this, I need to handle rebuilding the user's Jupyter server when they authenticated to Carina in a previous session. Right now I'm relying on having just authenticated, and then using the oauth token on the authenticator instance, which isn't guaranteed to exist.

```
Traceback (most recent call last):
      File "/opt/conda/lib/python3.5/site-packages/tornado/web.py", line 1445, in _execute
        result = yield result
      File "/opt/conda/lib/python3.5/site-packages/jupyterhub/handlers/base.py", line 484, in get
        yield self.spawn_single_user(current_user)
      File "/opt/conda/lib/python3.5/site-packages/jupyterhub/handlers/base.py", line 306, in spawn_single_user
        yield gen.with_timeout(timedelta(seconds=self.slow_spawn_timeout), f)
      File "/opt/conda/lib/python3.5/site-packages/jupyterhub/user.py", line 245, in spawn
        raise e
      File "/opt/conda/lib/python3.5/site-packages/jupyterhub/user.py", line 226, in spawn
        yield gen.with_timeout(timedelta(seconds=spawner.start_timeout), f)
      File "/opt/conda/lib/python3.5/site-packages/jupyterhub_carina/CarinaSpawner.py", line 68, in start
        yield self.create_cluster()
      File "/opt/conda/lib/python3.5/site-packages/jupyterhub_carina/CarinaSpawner.py", line 102, in create_cluster
        "Authorization": "Bearer {}".format(self.authenticator.oauth_token)}
    AttributeError: 'CarinaAuthenticator' object has no attribute 'oauth_token'
```

Now that we are using persistent hub storage, the token should be saved in the db for later use.
