### ISSUE TITLE
Test cluster limit reached scenario

### ISSUE THREAD

**Issue by carolynvs** [carolynvs/howtowhale#35]
Try out what happens for a user when they try to start a server and they are out of clusters.

**Comment by carolynvs** [comment]
**Logs**

```
jupyterhub     | [E 2016-05-27 21:13:01.565 JupyterHub CarinaOAuthClient:228] An error occurred executing PUT https://oauth.getcarina.com/clusters/jupyterhub:
jupyterhub     |     (500) b'{"message":"{\\"error\\": \\"cluster limit exceeded\\"}"}'
jupyterhub     |     Traceback (most recent call last):
jupyterhub     |       File "/opt/conda/lib/python3.5/site-packages/jupyterhub_carina/CarinaOAuthClient.py", line 225, in execute_request
jupyterhub     |         return (yield http_client.fetch(request, raise_error=raise_error))
nginx          | 24.15.200.84 - - [27/May/2016:21:13:01 +0000] "GET /jupyter/hub/user/carolynvs HTTP/1.1" 500 2707 "https://whaleinabox.carolynvs.com/jupyter/hub/home" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:46.0) Gecko/20100101 Firefox/46.0" "-"
jupyterhub     |     tornado.httpclient.HTTPError: HTTP 500: Internal Server Error
jupyterhub     |
jupyterhub     | [E 2016-05-27 21:13:01.569 JupyterHub CarinaSpawner:157] Startup for carolynvs failed!
jupyterhub     |     Traceback (most recent call last):
jupyterhub     |       File "/opt/conda/lib/python3.5/site-packages/jupyterhub_carina/CarinaSpawner.py", line 148, in start
jupyterhub     |         yield self.create_cluster()
jupyterhub     |       File "/opt/conda/lib/python3.5/site-packages/jupyterhub_carina/CarinaSpawner.py", line 169, in create_cluster
jupyterhub     |         yield self.carina_client.create_cluster(self.cluster_name)
jupyterhub     |       File "/opt/conda/lib/python3.5/site-packages/jupyterhub_carina/CarinaOAuthClient.py", line 110, in create_cluster
jupyterhub     |         response = yield self.execute_oauth_request(request)
jupyterhub     |       File "/opt/conda/lib/python3.5/site-packages/jupyterhub_carina/CarinaOAuthClient.py", line 194, in execute_oauth_request
jupyterhub     |         return (yield self.execute_request(request, raise_error))
jupyterhub     |       File "/opt/conda/lib/python3.5/site-packages/jupyterhub_carina/CarinaOAuthClient.py", line 225, in execute_request
jupyterhub     |         return (yield http_client.fetch(request, raise_error=raise_error))
jupyterhub     |     tornado.httpclient.HTTPError: HTTP 500: Internal Server Error
```

**User Message**

```
500 : Internal Server Error

Failed to start your server. Please contact admin.
```
